#!/bin/bash
#SBATCH -J 1_uce_probe_alignment
#SBATCH -A allocation
#SBATCH -N 1
#SBATCH -n 64
#SBATCH -c 1
#SBATCH -t 24:00:00
#SBATCH -p workq
#SBATCH -e ./error_out/_%J_%j.err
#SBATCH -o ./log_out/_%J_%j.log
#SBATCH --mail-type=ALL
#SBATCH --mail-user=my@email.com

module load conda

source activate ~/.conda/envs/phyluce-1.7.3
array=$(cat ~/sample.list)

phyluce_probe_run_multiple_lastzs_sqlite \
    --db phyluce-samples.sqlite \
    --output sample-genome-lastz \
    --scaffoldlist $array \
    --genome-base-path ./assemblies/ \
    --identity 60 \
    --coverage 50 \
    --probefile ./probe_set.fasta \
    --cores 64